language: objective-c
osx_image: xcode7.2
xcode_project: SwiftyProfiler.xcodeproj
xcode_scheme: SwiftyProfiler
script: xctool clean build test -project SwiftyProfiler.xcodeproj -scheme SwiftyProfiler -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
